### ISSUE TITLE
Moxxi's Bad Touch and Good Touch

### ISSUE THREAD

**Issue by maelstrom256** [BLCM/ModCabinet#2]
Moxxi (with patch) do not ever Good Touch offer, just Bad Touch one-two times and when Good Touch must be offered - animation just stops with no gun at hand (exit-enter location don't fix this).

Defaults were more reliable - just sell/drop/bank Touches and get new ones.

Last steam update, all DLC, GameSVoiCE's russian sound and subtitles.

**Comment by apocalyptech** [comment]
Hey there, closing out this ancient Issue.  If this is still something you're experiencing and would like addressed, feel free to stop by our Discord.  This "Issues" section is getting closed out, though, since it's just been stagnant for ages.
