### ISSUE TITLE
Possible replacement for the element of wolf/saint for wilhelm

### ISSUE THREAD

**Issue by SammichBro** [BLCM/ModCabinet#3]
Hey guys, I was wondering if you knew of a mod that changes the element of wilhelm's venom bolts from corrosive to cryo. If so, can you link it?

P.S. Loving the community patch

**Comment by apocalyptech** [comment]
Hello!  If this is something you're still interested in seeing, I'd recommend stopping by the Discord to ask about it.  This "Issues" section is getting closed out because it was never actually monitored properly anyway.
